### ISSUE TITLE
Type checking for integer has a bug

### ISSUE THREAD

**Issue by pakbaz** [Azure/azure-mobile-apps-cordova-client#58]
I have integer type defined and I have a type number defined for my model to be bound and save the data on local database. On Backend easy table its also type of number but when I try to save the data and sync to azure I get this error:
````
Exception has occurred: Error
Error: Converting value "1000" of type string to type integer is not supported.
    at serializeMember (http://192.168.50.188:8100/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:37136:15)
    at Object.serialize (http://192.168.50.188:8100/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:37085:45)
    at _upsert (http://192.168.50.188:8100/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:36501:47)
    at null.fn (http://192.168.50.188:8100/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:36804:34)
    at SQLitePluginTransaction.start (http://192.168.50.188:8100/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:331:12)
    at http://192.168.50.188:8100/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:145:32
    at t.invokeTask (http://192.168.50.188:8100/build/polyfills.js:3:15040)
    at r.runTask (http://192.168.50.188:8100/build/polyfills.js:3:10214)
    at e.invokeTask (http://192.168.50.188:8100/build/polyfills.js:3:16174)
    at i.isUsingGlobalCallback.invoke (http://192.168.50.188:8100/build/polyfills.js:3:16062)
````

**Comment by pakbaz** [comment]
never mind it turns out my model was updating to an string value.
